### ISSUE TITLE
Error when I visited the  /admin/graphs page

### ISSUE THREAD

**Issue by spoock1024** [isislab/CTFd#121]
127.0.0.1 - - [13/May/2016 02:14:52] "GET /admin/graphs HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aaron/CTFd/CTFd/utils.py", line 181, in decorated_function
    return f(*args, **kwargs)
  File "/home/aaron/CTFd/CTFd/admin.py", line 35, in admin_graphs
    return render_template('admin/graphs.html')
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aaron/CTFd/CTFd/templates/admin/graphs.html", line 1, in top-level template code
    {% extends "admin/base.html" %}
  File "/home/aaron/CTFd/CTFd/templates/admin/base.html", line 38, in top-level template code
    {% if can_create_container() %}
  File "/home/aaron/CTFd/CTFd/utils.py", line 392, in can_create_container
    output = subprocess.check_output(['docker', 'version'])
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

This is the error. When I try to enter into the /admin/praphs.I install the CTFd as it is suggested.So how can I solve the problem?

**Comment by ColdHeat** [comment]
Sorry about that, forgot to consider a case :)

**Comment by spoock1024** [comment]
I found that if I install the docker,the problem can be solved.But in this project,I don't know the how to use the docker.

**Comment by ColdHeat** [comment]
Just repull from master, this issue is resolved.
