### ISSUE TITLE
there is some error when installing

### ISSUE THREAD

**Issue by bitian** [isislab/CTFd#143]
I want to know,This program can be installed on the centos6.5 and What is the need for the python version.Python3.5 can use?

My system is centos6.5 ,python version is 3.5,but when I run "python serve.py",there is error:
Traceback (most recent call last):
  File "/usr/local/python3.5/lib/python3.5/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 337, in dbapi
    from sqlite3 import dbapi2 as sqlite  # try 2.5+ stdlib name.
  File "/usr/local/python3.5/lib/python3.5/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/python3.5/lib/python3.5/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: No module named '_sqlite3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "serve.py", line 2, in <module>
    app = create_app()
  File "/home/bitian/Desktop/CTFd-master/CTFd/__init__.py", line 28, in create_app
    if not database_exists(app.config['SQLALCHEMY_DATABASE_URI']) and not app.config['SQLALCHEMY_DATABASE_URI'].startswith('sqlite'):
  File "/usr/local/python3.5/lib/python3.5/site-packages/sqlalchemy_utils/functions/database.py", line 461, in database_exists
    engine = sa.create_engine(url)
  File "/usr/local/python3.5/lib/python3.5/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/python3.5/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/python3.5/lib/python3.5/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
  File "/usr/local/python3.5/lib/python3.5/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 334, in dbapi
    from pysqlite2 import dbapi2 as sqlite
ImportError: No module named 'pysqlite2'

**Comment by ColdHeat** [comment]
There should be no problem deploying on CentOS or Python 3. 

I think you seem to be missing a sqlalchemy dependency.
