### ISSUE TITLE
Error changing flags

### ISSUE THREAD

**Issue by Tiaonmmn** [isislab/CTFd#217]
I can't change my flag.Here's the traceback.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_excepti
on    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_
request    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_ex
ception    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_
request    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_reque
st    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/tiaonmmn/CTFd/CTFd/utils.py", line 196, in decorated_function
    return f(*args, **kwargs)
  File "/home/tiaonmmn/CTFd/CTFd/admin/keys.py", line 42, in admin_keys_view
    key_type = int(request.form.get('key_type'))
TypeError: int() argument must be a string or a number, not 'NoneType'
Also,if I delete one challenge,and recreate one with the same name,the flag won't change.How can I handle this?

**Comment by ColdHeat** [comment]
Are you using the latest copy of CTFd? Can you git pull? This seems like an error from an older commit.

**Comment by tjgerot** [comment]
@Tiaonmmn Looking at the that same file [`keys.py`](https://github.com/isislab/CTFd/blob/master/CTFd/admin/keys.py) the code on master for line 42 is: `if not keyid:` while line 42 in your file (according to the stack trace) is `key_type = int(request.form.get('key_type'))`.

Specifically, it seems you are using code from [commit fdb2c34](https://github.com/isislab/CTFd/commit/fdb2c34d889bd40e140d633bb2094657c29c342a).

**Comment by ColdHeat** [comment]
Thanks for the detective work @tjgerot. I think a new release is in order which users can be directed to.
