### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by mschwager** [isislab/CTFd#221]
I'm not sure what the procedure is for running tests. Maybe I need to have an actual server running?

Anyway, simply trying to run them fails:

```
$ pytest -sv
========================================= test session starts ==========================================
platform linux2 -- Python 2.7.12, pytest-3.0.6, py-1.4.32, pluggy-0.4.0 -- /usr/bin/python2.7
cachedir: .cache
rootdir: /home/matt/documents/CTFd, inifile: 
collected 19 items 

tests/test_user_facing.py::test_index PASSED
tests/test_user_facing.py::test_register_user PASSED
tests/test_user_facing.py::test_register_duplicate_teamname PASSED
tests/test_user_facing.py::test_register_duplicate_email PASSED
tests/test_user_facing.py::test_user_bad_login PASSED
tests/test_user_facing.py::test_user_login FAILED
tests/test_user_facing.py::test_user_isnt_admin FAILED
tests/test_user_facing.py::test_user_get_teams FAILED
tests/test_user_facing.py::test_user_get_scoreboard FAILED
tests/test_user_facing.py::test_user_get_scores FAILED
tests/test_user_facing.py::test_user_get_topteams FAILED
tests/test_user_facing.py::test_user_get_challenges FAILED
tests/test_user_facing.py::test_user_get_chals FAILED
tests/test_user_facing.py::test_user_get_solves_per_chal FAILED
tests/test_user_facing.py::test_user_get_solves FAILED
tests/test_user_facing.py::test_user_get_team_page FAILED
tests/test_user_facing.py::test_user_get_profile FAILED
tests/test_user_facing.py::test_user_get_logout FAILED
tests/test_user_facing.py::test_user_get_reset_password PASSED

=============================================== FAILURES ===============================================
___________________________________________ test_user_login ____________________________________________

    def test_user_login():
        """Can a registered user can login"""
        app = create_ctfd()
        with app.app_context():
            register_user(app)
            client = login_as_user(app)
>           r = client.get('/profile')

tests/test_user_facing.py:59: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python2.7/dist-packages/werkzeug/test.py:774: in get
    return self.open(*args, **kw)
/usr/local/lib/python2.7/dist-packages/flask/testing.py:108: in open
    follow_redirects=follow_redirects)
/usr/local/lib/python2.7/dist-packages/werkzeug/test.py:742: in open
    response = self.run_wsgi_app(environ, buffered=buffered)
/usr/local/lib/python2.7/dist-packages/werkzeug/test.py:659: in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
/usr/local/lib/python2.7/dist-packages/werkzeug/test.py:867: in run_wsgi_app
    app_iter = app(environ, start_response)
/usr/local/lib/python2.7/dist-packages/flask/app.py:1836: in __call__
    return self.wsgi_app(environ, start_response)
/usr/local/lib/python2.7/dist-packages/flask/app.py:1820: in wsgi_app
    response = self.make_response(self.handle_exception(e))
/usr/local/lib/python2.7/dist-packages/flask/app.py:1403: in handle_exception
    reraise(exc_type, exc_value, tb)
/usr/local/lib/python2.7/dist-packages/flask/app.py:1817: in wsgi_app
    response = self.full_dispatch_request()
/usr/local/lib/python2.7/dist-packages/flask/app.py:1477: in full_dispatch_request
    rv = self.handle_user_exception(e)
/usr/local/lib/python2.7/dist-packages/flask/app.py:1381: in handle_user_exception
    reraise(exc_type, exc_value, tb)
/usr/local/lib/python2.7/dist-packages/flask/app.py:1473: in full_dispatch_request
    rv = self.preprocess_request()
/usr/local/lib/python2.7/dist-packages/flask/app.py:1666: in preprocess_request
    rv = func()
CTFd/utils.py:122: in tracker
    track = Tracking.query.filter_by(ip=ip2long(get_ip()), team=session['id']).first()
CTFd/utils.py:286: in get_ip
    if not re.match(combined, addr): # IP is not trusted but we trust the proxies
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

pattern = '(^127\\.0\\.0\\.1$)|(^::1$)|(^fc00:)|(^10\\.)|(^172\\.(1[6-9]|2[0-9]|3[0-1])\\.)|(^192\\.168\\.)'
string = None, flags = 0

    def match(pattern, string, flags=0):
        """Try to apply the pattern at the start of the string, returning
        a match object, or None if no match was found."""
>       return _compile(pattern, flags).match(string)
E       TypeError: expected string or buffer

/usr/lib/python2.7/re.py:141: TypeError
```

All the tests that fail, fail with the same `TypeError`.

**Comment by ColdHeat** [comment]
Just run `nosetests` from the project directory.

**Comment by mschwager** [comment]
Hmm, still getting:

```
$ nosetests
Does the index page return a 200 by default ... ok
Can a user can be registered ... ok
A user shouldn't be able to use and already registered team name ... ok
A user shouldn't be able to use an already registered email address ... ok
A user should not be able to login with an incorrect password ... ok
Can a registered user can login ... ERROR

======================================================================
ERROR: Can a registered user can login
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/matt/documents/CTFd/tests/test_user_facing.py", line 59, in test_user_login
    r = client.get('/profile')
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 774, in get
    return self.open(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/flask/testing.py", line 108, in open
    follow_redirects=follow_redirects)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 742, in open
    response = self.run_wsgi_app(environ, buffered=buffered)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 659, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 867, in run_wsgi_app
    app_iter = app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1473, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1666, in preprocess_request
    rv = func()
  File "/home/matt/documents/CTFd/CTFd/utils.py", line 122, in tracker
    track = Tracking.query.filter_by(ip=ip2long(get_ip()), team=session['id']).first()
  File "/home/matt/documents/CTFd/CTFd/utils.py", line 286, in get_ip
    if not re.match(combined, addr): # IP is not trusted but we trust the proxies
  File "/usr/lib/python2.7/re.py", line 141, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or buffer
```
