### ISSUE TITLE
Usability issues

### ISSUE THREAD

**Issue by delta24** [isislab/CTFd#85]
Hi
If I log in as an admin, and then proceed to the root URL "/", then I get a `Uhh what did you just do?` (500) error. I think it should show the template corresponding to the "index" route.

Also if a team logs in **before** the CTF has started, then also a 500 error page is rendered just after login.

**Comment by ColdHeat** [comment]
You'll have to show me a stack trace or similar as I don't seem to be able to reproduce.

**Comment by delta24** [comment]
I am running this using Gunicorn + Nginx with config options (in a shell script)

```
exec gunicorn serve \
    --bind=unix:/root/gunicorn.sock \
    --log-level=debug \
    --log-file=/tmp/gunicorn.log \
    --access-logfile=/tmp/access.log \
    "$@"
```
and here is the stack trace:

```Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 130, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 187, in handle_request
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 171, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1473, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1666, in preprocess_request
    rv = func()
  File "/root/x/CTFd/views.py", line 22, in tracker
    if not Tracking.query.filter_by(ip=ip2long(request.remote_addr)).first():
  File "/root/x/CTFd/utils.py", line 212, in ip2long
    return unpack('!I', inet_aton(ip))[0]
error: illegal IP address string passed to inet_aton
```

**Comment by ColdHeat** [comment]
Hmm it's likely I'll never be able to reproduce this so you're going to have to do some testing on my behalf. 

If you could just print out ip before line 212 in utils.py and tell me what that says I can help you a little more. 

Perhaps this is an IPv6 issue?

**Comment by delta24** [comment]
No, I think this is an issue of Flask + Nginx. If a flask app is running behind Nginx, it will always report ip as `127.0.0.1`.
This might fix that. (http://stackoverflow.com/questions/12770950/flask-request-remote-addr-is-wrong-on-webfaction-and-not-showing-real-user-ip)
```
if request.headers.getlist("X-Forwarded-For"):
   ip = request.headers.getlist("X-Forwarded-For")[0]
else:
   ip = request.remote_addr
```

**Comment by ColdHeat** [comment]
There is already an issue where this is discussed but having the IP address as 127.0.0.1 shouldn't be causing a problem as I would've noticed it during development. 

Can you tell me what IP address is showing up in your logs?

**Comment by delta24** [comment]
So if I apply the (not so good for security) fix mentioned above, it correctly prints my ip. But then it causes a second error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 130, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 187, in handle_request
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 171, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1473, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1666, in preprocess_request
    rv = func()
  File "/root/x/CTFd/views.py", line 27, in tracker
    visit = Tracking(request.remote_addr, session['id'])
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/state.py", line 306, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/state.py", line 303, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/root/x/CTFd/models.py", line 189, in __init__
    self.ip = ip2long(ip)
  File "/root/x/CTFd/models.py", line 18, in ip2long
    return unpack('!I', inet_aton(ip))[0]
error: illegal IP address string passed to inet_aton
```

**Comment by ColdHeat** [comment]
Seems like the same error as before just in a different location. You should probably just let me know what IP address shows up so I can reproduce.

**Comment by delta24** [comment]
It is my private VPN ip address (through which I connect from my university network).
`128.199.xxx.xxx`

**Comment by ColdHeat** [comment]
I'll look further into this but I'm unable to reproduce:

~~~
>>> for x in range(256):
	for y in range(256):
		ip = ip2long('128.199.{}.{}'.format(x, y))

		
>>> 
~~~

**Comment by ColdHeat** [comment]
I'm reasonably sure 85e8a9d should address this issue. If anything it clears up some IP tracking issues.

**Comment by delta24** [comment]
So I pulled and tested, but it did not change anything. This works for me:

to `CTFd/__init__.py` add:

```
from werkzeug.contrib.fixers import ProxyFix
app.wsgi_app = ProxyFix(app.wsgi_app)
```

and the following Nginx conf:

```
proxy_set_header X-Forwarded-Proto https;
proxy_set_header X-Forwarded-Host your.project.domain.org;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_pass http://unix:/root/gunicorn.sock;
```

For course this fix is not for everybody (those who do not use a reverse proxy for deployment :P ) but you could add this to the wiki.
